name       : libtermkey
version    : 0.20
release    : 2
source     :
    - https://github.com/neovim/libtermkey/archive/v0.20.tar.gz : 88c38e0f1ed623dfc0f510ec697a0ff800c0ae64b43a34e6e7cb0a25d021417e
license    : MIT
component  : programming
summary    : Library for easy processing of keyboard entry from terminal-based programs
description: |
    Library for easy processing of keyboard entry from terminal-based programs
builddeps  :
    - pkgconfig(unibilium)
build      : |
    %make PREFIX=/usr LIBDIR=%libdir%
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
