name       : libtermkey
version    : 0.18
release    : 1
source     :
    - http://www.leonerd.org.uk/code/libtermkey/libtermkey-0.18.tar.gz : 239746de41c845af52bb3c14055558f743292dd6c24ac26c2d6567a5a6093926
license    : MIT
component  : programming
summary    : Library for easy processing of keyboard entry from terminal-based programs
description: |
    Library for easy processing of keyboard entry from terminal-based programs
builddeps  :
    - pkgconfig(unibilium)
build      : |
    %make PREFIX=/usr LIBDIR=%libdir%
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
